force-app/main/default/objects/Images__c/Images__c.object-meta.xml
<CustomObject>
    <label>Images</label>
    <nameField>
        <displayFormat>IMG-{0000000}</displayFormat>
        <label>Image No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Images</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Images__c/fields/Uploaded_to_CC__c.field-meta.xml
<CustomField>
    <fullName>Uploaded_to_CC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Uploaded to CC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Images__c/fields/Uploaded_to_CC_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Uploaded_to_CC_Date_Time__c</fullName>
    <label>Uploaded to CC Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/GFINT_ImagesTriggerHandler.cls
public class GFINT_ImagesTriggerHandler {
    
    public static void uncheckUploadedComCloudFieldOnIUOM(List<Images__c> theImagesList , Map<Id,Images__c> theImagesOldMap) {
        
        for(Images__c theImage : theImagesList) {
            
            if(theImagesOldMap.get(theImage.Id).Uploaded_to_CC__c && theImagesOldMap.get(theImage.Id).Uploaded_to_CC_Date_Time__c != null) {
                theImage.Uploaded_to_CC__c = false;
                theImage.Uploaded_to_CC_Date_Time__c = null;
            }
            
        }
        
    }
    
}