force-app/main/default/objects/Category__c/Category__c.object-meta.xml
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Category__c/fields/Page_Description__c.field-meta.xml
<CustomField>
    <fullName>Page_Description__c</fullName>
    <label>Page Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Category__c/fields/Page_Keywords__c.field-meta.xml
<CustomField>
    <fullName>Page_Keywords__c</fullName>
    <label>Page Keywords</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Category__c/fields/Subcategory__c.field-meta.xml
<CustomField>
    <fullName>Subcategory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subcategory</label>
    <referenceTo>Subcategory__c</referenceTo>
    <relationshipLabel>Categories</relationshipLabel>
    <relationshipName>Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GFERP__Item__c/GFERP__Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GFERP__Item__c/fields/adsBanners__c.field-meta.xml
<CustomField>
    <fullName>adsBanners__c</fullName>
    <label>adsBanners</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GFERP__Item__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <formula>GFERP__Item_Category__r.Parent__r.Parent__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GFERP__Item__c/fields/Display_Name_English__c.field-meta.xml
<CustomField>
    <fullName>Display_Name_English__c</fullName>
    <label>Display Name (English)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GFERP__Item__c/fields/GFERP__Base_Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Base_Unit_of_Measure__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The Base Unit of Measure for the item&apos;s inventory, such as EA, or LB.</inlineHelpText>
    <label>Base Unit of Measure</label>
    <referenceTo>GFERP__Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Warehouse_Product_del</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GFERP__Item__c/fields/GFERP__Description__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Description__c</fullName>
    <inlineHelpText>Use this field for the description of the item.</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/GFERP__Item__c/fields/GFERP__Item_Category__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Item_Category__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Use this field to classify items for filtering and reporting.  This field is the top level grouping for items.</inlineHelpText>
    <label>Item Category</label>
    <referenceTo>GFERP__Item_Category__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GFERP__Item__c/fields/GFERP__UPC__c.field-meta.xml
<CustomField>
    <fullName>GFERP__UPC__c</fullName>
    <inlineHelpText>UPC of the Item.</inlineHelpText>
    <label>UPC</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GFERP__Item__c/fields/Offers__c.field-meta.xml
<CustomField>
    <fullName>Offers__c</fullName>
    <label>Offers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GFERP__Item__c/fields/Page_Title__c.field-meta.xml
<CustomField>
    <fullName>Page_Title__c</fullName>
    <label>Page Title</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GFERP__Item__c/fields/Subcategory__c.field-meta.xml
<CustomField>
    <fullName>Subcategory__c</fullName>
    <formula>GFERP__Item_Category__r.Parent__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subcategory</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GFERP__Item_Category__c/GFERP__Item_Category__c.object-meta.xml
<CustomObject>
    <label>Item Category</label>
    <nameField>
        <label>Item Category</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GFERP__Item_Category__c/fields/GFERP__Description__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Description__c</fullName>
    <inlineHelpText>The description of the item category.</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/GFERP__Item_Category__c/fields/Image__c.field-meta.xml
<CustomField>
    <fullName>Image__c</fullName>
    <label>Image</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/GFERP__Item_Category__c/fields/Page_Keywords__c.field-meta.xml
<CustomField>
    <fullName>Page_Keywords__c</fullName>
    <label>Page Keywords</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/GFERP__Item_Category__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subcategory</label>
    <referenceTo>Subcategory__c</referenceTo>
    <relationshipLabel>Item Categories</relationshipLabel>
    <relationshipName>Item_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GFERP__Item_Category__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <precision>18</precision>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GFERP__Item_Unit_of_Measure__c/GFERP__Item_Unit_of_Measure__c.object-meta.xml
<CustomObject>
    <label>Item Unit of Measure</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Units of Measure</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GFERP__Item_Unit_of_Measure__c/fields/GFERP__Conversion__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Conversion__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>The number of units to convert to the item’s base UOM.</inlineHelpText>
    <label>Conversion</label>
    <precision>18</precision>
    <required>true</required>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GFERP__Item_Unit_of_Measure__c/fields/GFERP__Item__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Item__c</fullName>
    <inlineHelpText>The Item associated with this Item Unit of Measure.</inlineHelpText>
    <label>Item</label>
    <referenceTo>GFERP__Item__c</referenceTo>
    <relationshipLabel>Item Units of Measure</relationshipLabel>
    <relationshipName>Item_Unit_of_Measures1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GFERP__Item_Unit_of_Measure__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GFERP__Item_Unit_of_Measure__c/fields/Standard_Base_Price__c.field-meta.xml
<CustomField>
    <fullName>Standard_Base_Price__c</fullName>
    <label>List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GFERP__Item_Unit_of_Measure__c/fields/Uploaded_Available_Inventory__c.field-meta.xml
<CustomField>
    <fullName>Uploaded_Available_Inventory__c</fullName>
    <label>Uploaded Available Inventory</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GFERP__Item_Unit_of_Measure__c/fields/Uploaded_Online_Form_Date__c.field-meta.xml
<CustomField>
    <fullName>Uploaded_Online_Form_Date__c</fullName>
    <label>Uploaded Online Form Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/GFERP__Item_Unit_of_Measure__c/fields/Uploaded_Online_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Uploaded_Online_To_Date__c</fullName>
    <label>Uploaded Online To Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/GFERP__Item_Unit_of_Measure__c/fields/Uploaded_Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Uploaded_Sales_Price__c</fullName>
    <label>Uploaded Sales Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GFERP__Item_Unit_of_Measure__c/fields/Uploaded_to_CC_Inventory__c.field-meta.xml
<CustomField>
    <fullName>Uploaded_to_CC_Inventory__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Uploaded to CC Inventory</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GFERP__Item_Unit_of_Measure__c/fields/Uploaded_to_CC_Item__c.field-meta.xml
<CustomField>
    <fullName>Uploaded_to_CC_Item__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Uploaded to CC Item</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GFERP__Item_Unit_of_Measure__c/fields/Uploaded_to_CC_Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Uploaded_to_CC_Sales_Price__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Uploaded to CC Sales Price</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GFERP__Unit_of_Measure__c/GFERP__Unit_of_Measure__c.object-meta.xml
<CustomObject>
    <label>Unit of Measure</label>
    <nameField>
        <label>Unit of Measure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units of Measure</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GFERP__Unit_of_Measure__c/fields/GFERP__Description__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Description__c</fullName>
    <inlineHelpText>Use this field to give more detailed information about the unit of measure.</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Images__c/Images__c.object-meta.xml
<CustomObject>
    <label>Images</label>
    <nameField>
        <displayFormat>IMG-{0000000}</displayFormat>
        <label>Image No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Images</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Images__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item</label>
    <referenceTo>GFERP__Item__c</referenceTo>
    <relationshipName>SFCC_Images</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Images__c/fields/Item_Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Item_Unit_of_Measure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item Unit of Measure</label>
    <referenceTo>GFERP__Item_Unit_of_Measure__c</referenceTo>
    <relationshipName>SFCC_Images</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Images__c/fields/Path__c.field-meta.xml
<CustomField>
    <fullName>Path__c</fullName>
    <formula>IF(NOT(ISBLANK(Item__c)), Item__r.Name +&quot;_&quot; ,&apos;&apos;)  + IF(NOT(ISBLANK(Item_Unit_of_Measure__c )), Item_Unit_of_Measure__r.Name +&apos;_&apos; ,&apos;&apos;) + Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Path</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Images__c/fields/Variation_Value__c.field-meta.xml
<CustomField>
    <fullName>Variation_Value__c</fullName>
    <label>Variation Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Images__c/fields/View_Type__c.field-meta.xml
<CustomField>
    <fullName>View_Type__c</fullName>
    <label>View Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Large</fullName>
                <default>true</default>
                <label>Large</label>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Small</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subcategory__c/Subcategory__c.object-meta.xml
<CustomObject>
    <label>Subcategory</label>
    <nameField>
        <label>Subcategory</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subcategories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subcategory__c/fields/Display_Name_Arabic__c.field-meta.xml
<CustomField>
    <fullName>Display_Name_Arabic__c</fullName>
    <label>Display Name (Arabic)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subcategory__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Subcategories</relationshipLabel>
    <relationshipName>Subcategories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subcategory__c/fields/Rendering_Template__c.field-meta.xml
<CustomField>
    <fullName>Rendering_Template__c</fullName>
    <label>Rendering Template</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Subcategory__c/fields/Show_in_Menu__c.field-meta.xml
<CustomField>
    <fullName>Show_in_Menu__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show in Menu</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/GFINT_ComCloudHourlySchedulableBatch.cls
//GFINT_ComCloudHourlySchedulableBatchTest
public class GFINT_ComCloudHourlySchedulableBatch implements Database.Batchable<sObject>, Database.AllowsCallouts, Schedulable {
    
    Set<Id> theSelectedIUOM = new Set<Id>();
    Boolean IsForSelectedIUOM = false;
    
    public GFINT_ComCloudHourlySchedulableBatch() {
        
    }
    
    public GFINT_ComCloudHourlySchedulableBatch(Set<Id> theSelectedIdsOfIUOM, Boolean IsForOnlySelectedIUOM) {
        theSelectedIUOM = theSelectedIdsOfIUOM;
        IsForSelectedIUOM = IsForOnlySelectedIUOM;
    }
    
    public Database.QueryLocator start(Database.BatchableContext BC) {
        String theQuery = 'SELECT Id, Name,  GFERP__Item__c, GFERP__Conversion__c, Product_Type__c, Uploaded_Available_Inventory__c, GFERP__Item__r.GFERP__UPC__c, GFERP__Item__r.Display_Name_English__c, GFERP__Item__r.GFERP__Base_Unit_of_Measure__r.Name';
        theQuery = theQuery + ', GFERP__Item__r.Visible__c, Standard_Base_Price__c, GFERP__Item__r.GFERP__Description__c, GFERP__Item__r.Display_Name_Arabic__c, GFERP__Item__r.Ending_Date__c, GFERP__Item__r.Starting_Date__c, GFERP__Item__r.Long_Description__c, Uploaded_Sales_Price__c, Uploaded_Online_Form_Date__c, Uploaded_Online_To_Date__c';
        theQuery = theQuery + ', GFERP__Item__r.Category__c, GFERP__Item__r.Subcategory__c, GFERP__Item__r.GFERP__Item_Category__c, Uploaded_to_CC_Item__c, Uploaded_to_CC_Sales_Price__c, Uploaded_to_CC_Inventory__c';
        theQuery = theQuery + ', GFERP__Item__r.adsBanners__c,  GFERP__Item__r.Name,  GFERP__Item__r.Offers__c';
        theQuery = theQuery + ', (SELECT Id, Variation_Value__c, Path__c, Title__c, Item__c, Item_Unit_of_Measure__c, View_Type__c, Image__c FROM SFCC_Images__r)';
        theQuery = theQuery + ', GFERP__Item__r.GFERP__Item_Category__r.Parent__r.Parent__r.Name,  GFERP__Item__r.GFERP__Item_Category__r.Parent__r.Name,  GFERP__Item__r.GFERP__Item_Category__r.Name';
        theQuery = theQuery + ', GFERP__Item__r.GFERP__Item_Category__r.Parent__r.Parent__r.Online__c,  GFERP__Item__r.GFERP__Item_Category__r.Parent__r.Online__c,  GFERP__Item__r.GFERP__Item_Category__r.Online__c';
        theQuery = theQuery + ', GFERP__Item__r.GFERP__Item_Category__r.Parent__r.Parent__r.Position__c,  GFERP__Item__r.GFERP__Item_Category__r.Parent__r.Position__c,  GFERP__Item__r.GFERP__Item_Category__r.Position__c';
        theQuery = theQuery + ', GFERP__Item__r.GFERP__Item_Category__r.Parent__r.Parent__r.Rendering_Template__c,  GFERP__Item__r.GFERP__Item_Category__r.Parent__r.Rendering_Template__c,  GFERP__Item__r.GFERP__Item_Category__r.Rendering_Template__c';
        theQuery = theQuery + ', GFERP__Item__r.GFERP__Item_Category__r.Parent__r.Parent__r.Page_Title__c,  GFERP__Item__r.GFERP__Item_Category__r.Parent__r.Page_Title__c,  GFERP__Item__r.GFERP__Item_Category__r.Page_Title__c';
        theQuery = theQuery + ', GFERP__Item__r.GFERP__Item_Category__r.Parent__r.Parent__r.Short_Description__c,  GFERP__Item__r.GFERP__Item_Category__r.Parent__r.Short_Description__c,  GFERP__Item__r.GFERP__Item_Category__r.GFERP__Description__c';
        theQuery = theQuery + ', GFERP__Item__r.GFERP__Item_Category__r.Parent__r.Parent__r.Page_Description__c,  GFERP__Item__r.GFERP__Item_Category__r.Parent__r.Page_Description__c,  GFERP__Item__r.GFERP__Item_Category__r.Page_Description__c';
        theQuery = theQuery + ', GFERP__Item__r.GFERP__Item_Category__r.Parent__r.Parent__r.Image__c,  GFERP__Item__r.GFERP__Item_Category__r.Parent__r.Image__c,  GFERP__Item__r.GFERP__Item_Category__r.Image__c';
        theQuery = theQuery + ', GFERP__Item__r.GFERP__Item_Category__r.Parent__r.Parent__r.Show_in_Menu__c,  GFERP__Item__r.GFERP__Item_Category__r.Parent__r.Show_in_Menu__c,  GFERP__Item__r.GFERP__Item_Category__r.Show_in_Menu__c';
        theQuery = theQuery + ', GFERP__Item__r.GFERP__Item_Category__r.Parent__r.Parent__r.Page_Keywords__c,  GFERP__Item__r.GFERP__Item_Category__r.Parent__r.Page_Keywords__c,  GFERP__Item__r.GFERP__Item_Category__r.Page_Keywords__c';
        theQuery = theQuery + ', GFERP__Item__r.GFERP__Item_Category__r.Parent__r.Parent__r.Thumbnail__c,  GFERP__Item__r.GFERP__Item_Category__r.Parent__r.Thumbnail__c,  GFERP__Item__r.GFERP__Item_Category__r.Thumbnail__c';
        theQuery = theQuery + ', GFERP__Item__r.GFERP__Item_Category__r.Parent__r.Parent__r.Display_Name_Arabic__c,  GFERP__Item__r.GFERP__Item_Category__r.Parent__r.Display_Name_Arabic__c,  GFERP__Item__r.GFERP__Item_Category__r.Display_Name_Arabic__c';
        theQuery = theQuery + ', GFERP__Item__r.GFERP__Item_Category__r.Parent__r.Parent__r.Category_Id__c,  GFERP__Item__r.GFERP__Item_Category__r.Parent__r.Subcategory_Id__c,  GFERP__Item__r.GFERP__Item_Category__r.Fine_line_Id__c';
        theQuery = theQuery + ', GFERP__Item__r.GFERP__Country_of_Origin2__c, GFERP__Item__r.Searchable__c, GFERP__Item__r.GFERP__Brand__c, GFERP__Item__r.Manufacturer_SKU__c, GFERP__Item__r.Manufacturer_Name__c, GFERP__Item__r.Tax_Class_ID__c, GFERP__Item__r.GFERP__Item_Type__c';
        theQuery = theQuery + ', GFERP__Item__r.GFERP__Replenishment_System__c, GFERP__Item__r.GFERP__Inventory_Class__c, GFERP__Item__r.GFERP__Vendor__r.Name, GFERP__Item__r.GFERP__Vendor__c, GFERP__Item__r.Net_Weight__c, GFERP__Item__r.Capacity__c';
        theQuery = theQuery + ', GFERP__Item__r.Tags__c, GFERP__Item__r.GFERP__Base_Unit_of_Measure__c, GFERP__Item__r.isNew__c, GFERP__Item__r.GFERP__Lot_Tracked__c, GFERP__Item__r.Disabled_Shipping_Method__c';
        theQuery = theQuery + ', GFERP__Item__r.IsGiftVoucher__c';
        theQuery = theQuery + ' FROM GFERP__Item_Unit_of_Measure__c WHERE GFERP__Do_Not_Sell__c != true AND (Uploaded_to_CC_Item__c != true OR Uploaded_to_CC_Sales_Price__c != true OR Uploaded_to_CC_Inventory__c != true)';
        if(IsForSelectedIUOM){
            theQuery = theQuery + ' AND Id IN :theSelectedIUOM';
        } 
        return Database.getQueryLocator(theQuery);
        
    }
    
    public void execute(Database.BatchableContext BC, List<GFERP__Item_Unit_of_Measure__c> theItemUOMList) {
        Map<Id , List<GFERP__Item_Unit_of_Measure__c>> theItemId_ItemUOMListMap = new Map<Id , List<GFERP__Item_Unit_of_Measure__c>>();
        List<GFERP__Item_Unit_of_Measure__c> theUpdateItemUOMList = new List<GFERP__Item_Unit_of_Measure__c>();
        
        //Map of ItemId and List of Item UOM
        for(GFERP__Item_Unit_of_Measure__c theItemUOM : theItemUOMList) {
            if(!theItemId_ItemUOMListMap.Containskey(theItemUOM.GFERP__Item__c))
                theItemId_ItemUOMListMap.put(theItemUOM.GFERP__Item__c , new List<GFERP__Item_Unit_of_Measure__c>{ theItemUOM });
            else {
                theItemId_ItemUOMListMap.get(theItemUOM.GFERP__Item__c).add(theItemUOM);
            }
        }
        
        //Create Product XML
        System.enqueueJob(new GFINT_CreateMasterCatalogXML(theItemId_ItemUOMListMap, theItemUOMList));
        
        //Update Item UOM
        for(GFERP__Item_Unit_of_Measure__c theItemUOM : theItemUOMList) {
            
            Boolean theUpdate = false;
            if(!theItemUOM.Uploaded_to_CC_Item__c) { 
                theItemUOM.Uploaded_to_CC_Item__c = true;
                theItemUOM.Uploaded_to_CC_Item_Date_Time__c = System.now();
                theUpdate = true;
            }
            if(!theItemUOM.Uploaded_to_CC_Sales_Price__c) {
                theItemUOM.Uploaded_to_CC_Sales_Price__c = true;
                theItemUOM.Uploaded_to_CC_Sales_Price_Date_Time__c = System.now();
                theUpdate = true;
            }
            if(!theItemUOM.Uploaded_to_CC_Inventory__c) {
                theItemUOM.Uploaded_to_CC_Inventory__c = true;
                theItemUOM.Uploaded_to_CC_Inventory_Date_Time__c = System.now();
                theUpdate = true;
            }
            if(theUpdate) theUpdateItemUOMList.add(theItemUOM);
            
        }
        
        //DML on Item UOM
        if(!theUpdateItemUOMList.isEmpty()) update theUpdateItemUOMList;
        
    }
    
    public void finish(Database.BatchableContext BC) {
        
    }
    
    public void execute(SchedulableContext sc) {
        GFINT_UploadImageInCC theBatch = new GFINT_UploadImageInCC();
        Database.executeBatch(theBatch, 200);
    }
}