force-app/main/default/objects/Category__c/Category__c.object-meta.xml
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Category__c/fields/Subcategory__c.field-meta.xml
<CustomField>
    <fullName>Subcategory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subcategory</label>
    <referenceTo>Subcategory__c</referenceTo>
    <relationshipLabel>Categories</relationshipLabel>
    <relationshipName>Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GFERP__Item__c/GFERP__Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GFERP__Item__c/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <label>Capacity</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GFERP__Item__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <formula>GFERP__Item_Category__r.Parent__r.Parent__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GFERP__Item__c/fields/Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Display_Name__c</fullName>
    <label>Display Name</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/GFERP__Item__c/fields/GFERP__Base_Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Base_Unit_of_Measure__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The Base Unit of Measure for the item&apos;s inventory, such as EA, or LB.</inlineHelpText>
    <label>Base Unit of Measure</label>
    <referenceTo>GFERP__Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Warehouse_Product_del</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GFERP__Item__c/fields/GFERP__Blocked__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Checking this field will not allow any inventory transactions to be posted for this item.  An Item cannot be blocked unless there is 0 on hand qty. and 0 open transactions.</inlineHelpText>
    <label>Blocked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GFERP__Item__c/fields/GFERP__Costing_Method__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Costing_Method__c</fullName>
    <inlineHelpText>The costing method of the Item with two possible options: Standard or FIFO.</inlineHelpText>
    <label>Costing Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FIFO</fullName>
                <default>true</default>
                <label>FIFO</label>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GFERP__Item__c/fields/GFERP__Description__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Description__c</fullName>
    <inlineHelpText>Use this field for the description of the item.</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/GFERP__Item__c/fields/GFERP__Inventory_Class__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Inventory_Class__c</fullName>
    <inlineHelpText>The Inventory Class of the Item with three possible values: Raw Materials, Subassembly or Finished Goods.  This field will define what GL Account is used from the Company Setup when transactions are posted.</inlineHelpText>
    <label>Inventory Class</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Finished Goods</fullName>
                <default>true</default>
                <label>Finished Goods</label>
            </value>
            <value>
                <fullName>Subassembly</fullName>
            </value>
            <value>
                <fullName>Raw Materials</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GFERP__Item__c/fields/GFERP__Item_Category__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Item_Category__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Use this field to classify items for filtering and reporting.  This field is the top level grouping for items.</inlineHelpText>
    <label>Item Category</label>
    <referenceTo>GFERP__Item_Category__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GFERP__Item__c/fields/GFERP__Item_Type__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Item_Type__c</fullName>
    <inlineHelpText>The type of item with two possible values - Inventory or Service.  Inventory transaction will be maintained for Inventory items, but not for Service type items.</inlineHelpText>
    <label>Item Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GFERP__Item_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/GFERP__Item__c/fields/GFERP__Long_Description__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Long_Description__c</fullName>
    <inlineHelpText>A picture of the item can be uploaded here.</inlineHelpText>
    <label>Item Picture</label>
    <length>2000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/GFERP__Item__c/fields/GFERP__Replenishment_System__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Replenishment_System__c</fullName>
    <inlineHelpText>Enter the default method to replenish the inventory for the item with two possible options: Purchase or Work Order.  if the item can be both purchased and manufactured, enter Work Order.</inlineHelpText>
    <label>Replenishment System</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Purchase</fullName>
                <default>true</default>
                <label>Purchase</label>
            </value>
            <value>
                <fullName>Work Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GFERP__Item__c/fields/GFERP__Standard_Base_Cost__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Standard_Base_Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>The Standard Base Cost for the item.</inlineHelpText>
    <label>Standard Base Cost</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GFERP__Item__c/fields/GFERP__Standard_Base_Price__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Standard_Base_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>The Standard Base Price for the item.</inlineHelpText>
    <label>Standard Base Price</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GFERP__Item__c/fields/GFERP__Standard_Material_Base_Cost__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Standard_Material_Base_Cost__c</fullName>
    <inlineHelpText>The Standard Material Base Cost for the item.</inlineHelpText>
    <label>Standard Material Base Cost</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GFERP__Item__c/fields/GFERP__UPC__c.field-meta.xml
<CustomField>
    <fullName>GFERP__UPC__c</fullName>
    <inlineHelpText>UPC of the Item.</inlineHelpText>
    <label>UPC</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GFERP__Item__c/fields/GFERP__Work_Center__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Work_Center__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked, this service item is used as a work center for the routing.</inlineHelpText>
    <label>Work Center</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GFERP__Item__c/fields/Net_Weight__c.field-meta.xml
<CustomField>
    <fullName>Net_Weight__c</fullName>
    <label>Net Weight</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GFERP__Item__c/fields/Subcategory__c.field-meta.xml
<CustomField>
    <fullName>Subcategory__c</fullName>
    <formula>GFERP__Item_Category__r.Parent__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subcategory</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GFERP__Item_Category__c/GFERP__Item_Category__c.object-meta.xml
<CustomObject>
    <label>Item Category</label>
    <nameField>
        <label>Item Category</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GFERP__Item_Category__c/fields/GFERP__Description__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Description__c</fullName>
    <inlineHelpText>The description of the item category.</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/GFERP__Item_Category__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subcategory</label>
    <referenceTo>Subcategory__c</referenceTo>
    <relationshipLabel>Item Categories</relationshipLabel>
    <relationshipName>Item_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GFERP__Item_Unit_of_Measure__c/GFERP__Item_Unit_of_Measure__c.object-meta.xml
<CustomObject>
    <label>Item Unit of Measure</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Units of Measure</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GFERP__Item_Unit_of_Measure__c/fields/GFERP__Item__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Item__c</fullName>
    <inlineHelpText>The Item associated with this Item Unit of Measure.</inlineHelpText>
    <label>Item</label>
    <referenceTo>GFERP__Item__c</referenceTo>
    <relationshipLabel>Item Units of Measure</relationshipLabel>
    <relationshipName>Item_Unit_of_Measures1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GFERP__Item_Unit_of_Measure__c/fields/GFERP__Type__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Type__c</fullName>
    <formula>Text( GFERP__Unit_of_Measure__r.GFERP__Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The type that is associated with the Unit of Measure.</inlineHelpText>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GFERP__Item_Unit_of_Measure__c/fields/GFERP__Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Unit_of_Measure__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The Unit of Measure that is associated with this Item Unit of Measure.</inlineHelpText>
    <label>Unit of Measure</label>
    <referenceTo>GFERP__Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Item Unit of Measures</relationshipLabel>
    <relationshipName>Item_Unit_of_Measures</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GFERP__Unit_of_Measure__c/GFERP__Unit_of_Measure__c.object-meta.xml
<CustomObject>
    <label>Unit of Measure</label>
    <nameField>
        <label>Unit of Measure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units of Measure</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GFERP__Unit_of_Measure__c/fields/GFERP__Description__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Description__c</fullName>
    <inlineHelpText>Use this field to give more detailed information about the unit of measure.</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/GFERP__Unit_of_Measure__c/fields/GFERP__Type__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Type__c</fullName>
    <inlineHelpText>The types of the Unit of Measure can be Length, Area, Volume, Weight, Time, Price, Package, Batch or Other.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GFERP__Unit_of_Measure_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subcategory__c/Subcategory__c.object-meta.xml
<CustomObject>
    <label>Subcategory</label>
    <nameField>
        <label>Subcategory</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subcategories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subcategory__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Subcategories</relationshipLabel>
    <relationshipName>Subcategories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GFINT_DownloadXMLtoLocalConTest.cls
@isTest
public class GFINT_DownloadXMLtoLocalConTest {
    
    @testSetup
    public static void setup() {
        
        XMLUploadToCommerce__c testCommerceCloud = new XMLUploadToCommerce__c();
        testCommerceCloud.Name = 'XMLUploadAPI';
        testCommerceCloud.Username__c = 'ashish.aggarwal@goldfinchcloudsolutions.com';
        testCommerceCloud.Password__c = 'Abs@1234';
        testCommerceCloud.EndPoint__c = 'https://bgkv-001.sandbox.us01.dx.commercecloud.salesforce.com/on/demandware.servlet/webdav/Sites/impex/src/uploads/fromGoldFinch/';
        insert testCommerceCloud;
        
        GFERP__Unit_of_Measure__c UnitMeasureRecord1 = new GFERP__Unit_of_Measure__c( Name = 'CS', GFERP__Type__c = 'Piece' );
        insert UnitMeasureRecord1;
        
        GFERP__Unit_of_Measure__c UnitMeasureRecord2 = new GFERP__Unit_of_Measure__c( Name = 'EA', GFERP__Type__c = 'Piece' );
        insert UnitMeasureRecord2;
        
        List<GFERP__Item__c> theItemList = new List<GFERP__Item__c>();
        
        Category__c testCategory = new Category__c();
        testCategory.Display_Name__c = 'Grains';
        insert testCategory;
        
        Subcategory__c testSubCategory = new Subcategory__c();
        testSubCategory.Display_Name__c = 'SUB Grains';
        testSubCategory.Parent__c = testCategory.Id;
        insert testSubCategory;
        
        GFERP__Item_Category__c ItemCategoryRecord = new GFERP__Item_Category__c ();
        testSubCategory.Display_Name__c = 'Fine Grains';
        //ItemCategoryRecord.Category__c = testCategory.Id;
        ItemCategoryRecord.Parent__c = testSubCategory.Id;
        ItemCategoryRecord.Name = 'Fine Grains';
        insert ItemCategoryRecord;
        
        for(Integer i = 0; i<100; i++) {
            
            GFERP__Item__c ItemRecord = new GFERP__Item__c(
                Name = '700'+i,
                GFERP__Item_Category__c = ItemCategoryRecord.Id,
                GFERP__Description__c = 'Chocolate Cake'+i,
                GFERP__Base_Unit_of_Measure__c = UnitMeasureRecord1.Id,
                GFERP__Work_Center__c = false,
                GFERP__Blocked__c = false,
                Starting_Date__c = System.today(),
                Net_Weight__c = '10',
                Capacity__c = '1',
                Tags__c = 'Test Tag',
                Ending_Date__c = System.today().addDays(10),
                GFERP__Replenishment_System__c = 'Work Order',
                GFERP__Costing_Method__c = 'Standard',
                GFERP__Inventory_Class__c = 'Finished Goods',
                GFERP__Standard_Base_Cost__c = 1,
                GFERP__Standard_Material_Base_Cost__c = 1,
                GFERP__Standard_Base_Price__c = 10,
                GFERP__Item_Type__c = 'Inventory',
                GFERP__Long_Description__c = '<image src="https://autodesk.i.lithium.com/t5/image/serverpage/image-id/516281i74784B88B7BE4B86/image-size/large?v=1.0&px=999"/>',
                GFERP__UPC__c = '888444555444'
            );
            theItemList.add(ItemRecord);
        }
        insert theItemList;  
        
        List<GFERP__Item_Unit_of_Measure__c> testItemUnitMeasureList = new List<GFERP__Item_Unit_of_Measure__c>();
        for(GFERP__Item__c ItemRecord : theItemList) {
            
            GFERP__Item_Unit_of_Measure__c  ItemUnitMeasureRecord = new GFERP__Item_Unit_of_Measure__c(
                Name = 'CS',
                GFERP__Conversion__c = 1,
                GFERP__Item__c = ItemRecord.Id,
                GFERP__Unit_of_Measure__c = UnitMeasureRecord1.Id,
                GFERP__Do_Not_Sell__c = false
            );
            testItemUnitMeasureList.add(ItemUnitMeasureRecord);
            
            GFERP__Item_Unit_of_Measure__c  ItemUnitMeasureRecord1 = new GFERP__Item_Unit_of_Measure__c(
                Name = 'EA',
                GFERP__Conversion__c = 1,
                GFERP__Item__c = ItemRecord.Id,
                GFERP__Unit_of_Measure__c = UnitMeasureRecord2.Id,
                GFERP__Do_Not_Sell__c = false
            );
            testItemUnitMeasureList.add(ItemUnitMeasureRecord1);
            
        }
        insert testItemUnitMeasureList;
    }
    
    @isTest
    public Static void downloadableXMLtoLocalControllerTest() {
        
        List<GFERP__Item__c> testItemUOMList = [SELECT Id FROM GFERP__Item__c limit 20];
        
        Set<Id> testItemIdSet = new Set<Id>();
        
        for(GFERP__Item__c testItem : testItemUOMList) {
            testItemIdSet.add(testItem.Id);
        }
        
        test.startTest();
        ApexPages.StandardSetController stdSetController = new ApexPages.StandardSetController(testItemUOMList);
        stdSetController.setSelected(testItemUOMList);
        GFINT_DownloadXMLtoLocalController testApex = new GFINT_DownloadXMLtoLocalController(stdSetController);
        testApex.returnBack();
        GFINT_DownloadXMLtoLocalController.createXMLFiles(JSON.serialize(testItemIdSet));
        test.stopTest(); 
        
    }
}