force-app/main/default/objects/GFERP__Item__c/GFERP__Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GFERP__Item_Unit_of_Measure__c/GFERP__Item_Unit_of_Measure__c.object-meta.xml
<CustomObject>
    <label>Item Unit of Measure</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Units of Measure</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GFERP__Item_Unit_of_Measure__c/fields/GFERP__Item__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Item__c</fullName>
    <inlineHelpText>The Item associated with this Item Unit of Measure.</inlineHelpText>
    <label>Item</label>
    <referenceTo>GFERP__Item__c</referenceTo>
    <relationshipLabel>Item Units of Measure</relationshipLabel>
    <relationshipName>Item_Unit_of_Measures1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/GFINT_ForceSendXMLToSFCCController.cls
//GFINT_ComCloudItemInventoryBatchTest
public class GFINT_ForceSendXMLToSFCCController {
    private ApexPages.StandardSetController standardSetController;
    public Integer theItemCount { get; set; }
    Set<Id> itemSelectedIds;
    
    public GFINT_ForceSendXMLToSFCCController(ApexPages.StandardSetController controller) {
        theItemCount = 0;
        standardSetController = controller;
        itemSelectedIds = new Set<Id>();
        for (GFERP__Item__c theItem : (GFERP__Item__c[]) standardSetController.getSelected()) {
            itemSelectedIds.add(theItem.Id);
            theItemCount += 1;
        }
    }
    
    public pagereference callNightlyBatch() {
        List<GFERP__Item_Unit_of_Measure__c> theSelectedIUOMList = [SELECT Id FROM GFERP__Item_Unit_of_Measure__c WHERE GFERP__Item__c IN: itemSelectedIds];
        
        if(!theSelectedIUOMList.isEmpty()) {
            GFINT_ComCloudNightlySchedulableBatch theNightlyBatchObj = new GFINT_ComCloudNightlySchedulableBatch(theSelectedIUOMList);
            Database.executeBatch(theNightlyBatchObj);
        }
        
        return new ApexPages.Action('{!List}').invoke();
    }
    
    public PageReference returnBack() {
        return new ApexPages.Action('{!List}').invoke();
    }
}