force-app/main/default/objects/GFERP__Item__c/GFERP__Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GFERP__Item_Unit_of_Measure__c/GFERP__Item_Unit_of_Measure__c.object-meta.xml
<CustomObject>
    <label>Item Unit of Measure</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Units of Measure</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GFERP__Item_Unit_of_Measure__c/fields/GFERP__Do_Not_Sell__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Do_Not_Sell__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Checking this field will not allow this Item Unit of Measure to be used on a Sales Order.</inlineHelpText>
    <label>Do Not Sell</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GFERP__Item_Unit_of_Measure__c/fields/GFERP__Item__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Item__c</fullName>
    <inlineHelpText>The Item associated with this Item Unit of Measure.</inlineHelpText>
    <label>Item</label>
    <referenceTo>GFERP__Item__c</referenceTo>
    <relationshipLabel>Item Units of Measure</relationshipLabel>
    <relationshipName>Item_Unit_of_Measures1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GFERP__Item_Unit_of_Measure__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GFERP__Item_Unit_of_Measure__c/fields/Uploaded_to_CC_Item__c.field-meta.xml
<CustomField>
    <fullName>Uploaded_to_CC_Item__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Uploaded to CC Item</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GFERP__Item_Unit_of_Measure__c/fields/Uploaded_to_CC_Item_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Uploaded_to_CC_Item_Date_Time__c</fullName>
    <label>Uploaded to CC Item Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/GFINT_ItemUnitofMeasureTriggerHandler.cls
//Test Class: GFINT_ItemUnitofMeasureTriHandlerTest
public class GFINT_ItemUnitofMeasureTriggerHandler {
    
    public static void uncheckUploadedComCloudFieldOnIUOM(List<GFERP__Item_Unit_of_Measure__c> theItemUOMList , Map<Id,GFERP__Item_Unit_of_Measure__c> theItemUOMOldMap) {
        
        for(GFERP__Item_Unit_of_Measure__c theItemUOM : theItemUOMList) {
            
            if(theItemUOMOldMap.get(theItemUOM.Id).Uploaded_to_CC_Item__c && theItemUOMOldMap.get(theItemUOM.Id).Uploaded_to_CC_Item_Date_Time__c != null) {
                theItemUOM.Uploaded_to_CC_Item__c = false;
                theItemUOM.Uploaded_to_CC_Item_Date_Time__c = null;
            }
            
        }
        
    }
    
    public static void updateProductTypeForInsertUpdateUndelete(List<GFERP__Item_Unit_of_Measure__c> theItemUOMList) {
        
        helperMethodToUpdateProductType(theItemUOMList, false);
        
    }
    
    public static void updateProductTypeForDelete(List<GFERP__Item_Unit_of_Measure__c> theItemUOMList) {
        
        helperMethodToUpdateProductType(theItemUOMList, True);
        
    }
    
    public static void helperMethodToUpdateProductType(List<GFERP__Item_Unit_of_Measure__c> theItemUOMList, Boolean IsDeleteTrigger) {
        List<GFERP__Item_Unit_of_Measure__c> theItemUOMFutureUpdateList = new List<GFERP__Item_Unit_of_Measure__c>();
        Map<Id, List<GFERP__Item_Unit_of_Measure__c>> theItemId_ItemUOMListMap = new Map<Id, List<GFERP__Item_Unit_of_Measure__c>>();
        Set<Id> theItemUOMIdSet = new Set<Id>();
        Set<Id> theItemIdSet = new Set<Id>();
        
        //create Map for new itemUOM
        for(GFERP__Item_Unit_of_Measure__c theItemUOM : theItemUOMList) {
            
            theItemUOMIdSet.add(theItemUOM.Id);
            theItemIdSet.add(theItemUOM.GFERP__Item__c);
            
        }
        
        String theQuery = 'SELECT Id, GFERP__Item__c, Product_Type__c, GFERP__Do_Not_Sell__c FROM GFERP__Item_Unit_of_Measure__c WHERE GFERP__Item__c IN: theItemIdSet AND GFERP__Do_Not_Sell__c != True'; 
        if(IsDeleteTrigger) theQuery += '  AND Id NOT IN : theItemUOMIdSet';
        List<GFERP__Item_Unit_of_Measure__c> theAlreadyExistsItemUOMList = (List<GFERP__Item_Unit_of_Measure__c>) Database.query(theQuery);

        for(GFERP__Item_Unit_of_Measure__c theItemUOM : theAlreadyExistsItemUOMList) {
            
            if(!theItemId_ItemUOMListMap.containsKey(theItemUOM.GFERP__Item__c)) {
                theItemId_ItemUOMListMap.put(theItemUOM.GFERP__Item__c , new List<GFERP__Item_Unit_of_Measure__c>{theItemUOM});
            }
            else {
                theItemId_ItemUOMListMap.get(theItemUOM.GFERP__Item__c).add(theItemUOM);
            }
        }
        
        for(GFERP__Item_Unit_of_Measure__c theItemUOM : theAlreadyExistsItemUOMList) {
            
            if(theItemId_ItemUOMListMap.Containskey(theItemUOM.GFERP__Item__c) && theItemId_ItemUOMListMap.get(theItemUOM.GFERP__Item__c).size() > 1) {
                
                if(theItemUOM.Product_Type__c != 'Variant') {
                    theItemUOM.Product_Type__c = 'Variant';
                    theItemUOMFutureUpdateList.add(theItemUOM);
                }
            }
            else if(theItemId_ItemUOMListMap.get(theItemUOM.GFERP__Item__c).size() == 1 && theItemUOM.Product_Type__c != 'Item') {
                theItemUOM.Product_Type__c = 'Item';
                theItemUOMFutureUpdateList.add(theItemUOM);
            }
        }
        
        if(!theItemUOMFutureUpdateList.isEmpty()) {
            if(System.isFuture() || System.isBatch()) {
                update theItemUOMFutureUpdateList;
            }else {
                updateVariantInsubItemUOMWithFuture(json.serialize(theItemUOMFutureUpdateList));
            }
        }
        
    }
    
    @future(Callout=true) 
    public static void updateVariantInsubItemUOMWithFuture(String jsonString) {
        
        List<GFERP__Item_Unit_of_Measure__c> theItemUOMList;
        if(!String.isEmpty(jsonString)) theItemUOMList = (List<GFERP__Item_Unit_of_Measure__c>)Json.deserialize(jsonString,List<GFERP__Item_Unit_of_Measure__c>.class);
        if(!theItemUOMList.isEmpty()) update theItemUOMList;
        
    }
    
    public static void updateProductTypeForDonotSell(List<GFERP__Item_Unit_of_Measure__c> theItemUOMList) {
        
        for(GFERP__Item_Unit_of_Measure__c theItemUOM : theItemUOMList) {
            
            if(theItemUOM.GFERP__Do_Not_Sell__c) {
                theItemUOM.Product_Type__c = null;
            }
            
        }
        
    }
    
}