force-app/main/default/objects/GFERP__Item__c/GFERP__Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GFERP__Item__c/fields/GFERP__Base_Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Base_Unit_of_Measure__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The Base Unit of Measure for the item&apos;s inventory, such as EA, or LB.</inlineHelpText>
    <label>Base Unit of Measure</label>
    <referenceTo>GFERP__Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Warehouse_Product_del</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GFERP__Item__c/fields/GFERP__Blocked__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Checking this field will not allow any inventory transactions to be posted for this item.  An Item cannot be blocked unless there is 0 on hand qty. and 0 open transactions.</inlineHelpText>
    <label>Blocked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GFERP__Item__c/fields/GFERP__Costing_Method__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Costing_Method__c</fullName>
    <inlineHelpText>The costing method of the Item with two possible options: Standard or FIFO.</inlineHelpText>
    <label>Costing Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FIFO</fullName>
                <default>true</default>
                <label>FIFO</label>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GFERP__Item__c/fields/GFERP__Description__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Description__c</fullName>
    <inlineHelpText>Use this field for the description of the item.</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/GFERP__Item__c/fields/GFERP__Inventory_Class__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Inventory_Class__c</fullName>
    <inlineHelpText>The Inventory Class of the Item with three possible values: Raw Materials, Subassembly or Finished Goods.  This field will define what GL Account is used from the Company Setup when transactions are posted.</inlineHelpText>
    <label>Inventory Class</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Finished Goods</fullName>
                <default>true</default>
                <label>Finished Goods</label>
            </value>
            <value>
                <fullName>Subassembly</fullName>
            </value>
            <value>
                <fullName>Raw Materials</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GFERP__Item__c/fields/GFERP__Item_Type__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Item_Type__c</fullName>
    <inlineHelpText>The type of item with two possible values - Inventory or Service.  Inventory transaction will be maintained for Inventory items, but not for Service type items.</inlineHelpText>
    <label>Item Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GFERP__Item_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/GFERP__Item__c/fields/GFERP__Long_Description__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Long_Description__c</fullName>
    <inlineHelpText>A picture of the item can be uploaded here.</inlineHelpText>
    <label>Item Picture</label>
    <length>2000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/GFERP__Item__c/fields/GFERP__Replenishment_System__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Replenishment_System__c</fullName>
    <inlineHelpText>Enter the default method to replenish the inventory for the item with two possible options: Purchase or Work Order.  if the item can be both purchased and manufactured, enter Work Order.</inlineHelpText>
    <label>Replenishment System</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Purchase</fullName>
                <default>true</default>
                <label>Purchase</label>
            </value>
            <value>
                <fullName>Work Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GFERP__Item__c/fields/GFERP__Standard_Base_Cost__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Standard_Base_Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>The Standard Base Cost for the item.</inlineHelpText>
    <label>Standard Base Cost</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GFERP__Item__c/fields/GFERP__Standard_Base_Price__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Standard_Base_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>The Standard Base Price for the item.</inlineHelpText>
    <label>Standard Base Price</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GFERP__Item__c/fields/GFERP__Standard_Material_Base_Cost__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Standard_Material_Base_Cost__c</fullName>
    <inlineHelpText>The Standard Material Base Cost for the item.</inlineHelpText>
    <label>Standard Material Base Cost</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GFERP__Item__c/fields/GFERP__UPC__c.field-meta.xml
<CustomField>
    <fullName>GFERP__UPC__c</fullName>
    <inlineHelpText>UPC of the Item.</inlineHelpText>
    <label>UPC</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GFERP__Item__c/fields/GFERP__Work_Center__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Work_Center__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked, this service item is used as a work center for the routing.</inlineHelpText>
    <label>Work Center</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GFERP__Item_Unit_of_Measure__c/GFERP__Item_Unit_of_Measure__c.object-meta.xml
<CustomObject>
    <label>Item Unit of Measure</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Units of Measure</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GFERP__Item_Unit_of_Measure__c/fields/GFERP__Conversion__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Conversion__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>The number of units to convert to the item’s base UOM.</inlineHelpText>
    <label>Conversion</label>
    <precision>18</precision>
    <required>true</required>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GFERP__Item_Unit_of_Measure__c/fields/GFERP__Do_Not_Sell__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Do_Not_Sell__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Checking this field will not allow this Item Unit of Measure to be used on a Sales Order.</inlineHelpText>
    <label>Do Not Sell</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GFERP__Item_Unit_of_Measure__c/fields/GFERP__Item__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Item__c</fullName>
    <inlineHelpText>The Item associated with this Item Unit of Measure.</inlineHelpText>
    <label>Item</label>
    <referenceTo>GFERP__Item__c</referenceTo>
    <relationshipLabel>Item Units of Measure</relationshipLabel>
    <relationshipName>Item_Unit_of_Measures1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GFERP__Item_Unit_of_Measure__c/fields/GFERP__Type__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Type__c</fullName>
    <formula>Text( GFERP__Unit_of_Measure__r.GFERP__Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The type that is associated with the Unit of Measure.</inlineHelpText>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GFERP__Item_Unit_of_Measure__c/fields/GFERP__Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Unit_of_Measure__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The Unit of Measure that is associated with this Item Unit of Measure.</inlineHelpText>
    <label>Unit of Measure</label>
    <referenceTo>GFERP__Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Item Unit of Measures</relationshipLabel>
    <relationshipName>Item_Unit_of_Measures</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GFERP__Item_Unit_of_Measure__c/fields/Uploaded_Online_Form_Date__c.field-meta.xml
<CustomField>
    <fullName>Uploaded_Online_Form_Date__c</fullName>
    <label>Uploaded Online Form Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/GFERP__Item_Unit_of_Measure__c/fields/Uploaded_Online_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Uploaded_Online_To_Date__c</fullName>
    <label>Uploaded Online To Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/GFERP__Item_Unit_of_Measure__c/fields/Uploaded_Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Uploaded_Sales_Price__c</fullName>
    <label>Uploaded Sales Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GFERP__Item_Unit_of_Measure__c/fields/Uploaded_to_CC_Item__c.field-meta.xml
<CustomField>
    <fullName>Uploaded_to_CC_Item__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Uploaded to CC Item</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GFERP__Item_Unit_of_Measure__c/fields/Uploaded_to_CC_Item_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Uploaded_to_CC_Item_Date_Time__c</fullName>
    <label>Uploaded to CC Item Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/GFERP__Unit_of_Measure__c/GFERP__Unit_of_Measure__c.object-meta.xml
<CustomObject>
    <label>Unit of Measure</label>
    <nameField>
        <label>Unit of Measure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units of Measure</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GFERP__Unit_of_Measure__c/fields/GFERP__Description__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Description__c</fullName>
    <inlineHelpText>Use this field to give more detailed information about the unit of measure.</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/GFERP__Unit_of_Measure__c/fields/GFERP__Type__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Type__c</fullName>
    <inlineHelpText>The types of the Unit of Measure can be Length, Area, Volume, Weight, Time, Price, Package, Batch or Other.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GFERP__Unit_of_Measure_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/GFINT_SalesPriceEntryTriggerHandlerTest.cls
@isTest
public class GFINT_SalesPriceEntryTriggerHandlerTest {
    @testSetup
    public static void setup() {
        
        GFERP__Demand_Planning_Setup__c DemandPlanningSetupRecord = new GFERP__Demand_Planning_Setup__c(
            Name = 'Default',
            GFERP__Periods_to_Re_Forecast__c = 4,
            GFERP__Periods_to_Forecast__c = 12,
            GFERP__Inventory_Period_Type__c = 'By Week',
            GFERP__Periods_to_Run_Supply_Plan__c = 6
        );
        insert DemandPlanningSetupRecord;
        
        List<GFERP__Item_Unit_of_Measure__c> testItemUOMList = new List<GFERP__Item_Unit_of_Measure__c>();
        List<GFERP__Unit_of_Measure__c> testUOMList = new List<GFERP__Unit_of_Measure__c>();
        List<GFERP__Sales_Price_Entry__c> testSalesPriceEntryRecordList = new List<GFERP__Sales_Price_Entry__c>();
        
        GFERP__Currency__c CurrencyRecord = new  GFERP__Currency__c(
            Name = 'KWD'
        );
        insert CurrencyRecord;
        
        GFERP__Unit_of_Measure__c UnitMeasureRecord = new GFERP__Unit_of_Measure__c(Name = 'EA',
                                                                                    GFERP__Type__c = 'Piece');
        
        testUOMList.add(UnitMeasureRecord);
        
        GFERP__Unit_of_Measure__c UnitMeasureRecord1 = new GFERP__Unit_of_Measure__c(Name = 'Pack',
                                                                                     GFERP__Type__c = 'Piece');
        testUOMList.add(UnitMeasureRecord1);
        
        insert testUOMList;
        
        GFERP__Item__c ItemRecord = new GFERP__Item__c(
            Name = '7002',
            GFERP__Description__c = 'Chocolate Cake',
            GFERP__Base_Unit_of_Measure__c = UnitMeasureRecord.Id,
            GFERP__Work_Center__c = false,
            GFERP__Blocked__c = false,
            GFERP__Replenishment_System__c = 'Work Order',
            GFERP__Costing_Method__c = 'Standard',
            GFERP__Inventory_Class__c = 'Finished Goods',
            GFERP__Standard_Base_Cost__c = 1,
            GFERP__Standard_Material_Base_Cost__c = 1,
            GFERP__Standard_Base_Price__c = 10,
            GFERP__Item_Type__c = 'Inventory',
            GFERP__Long_Description__c = '<image src="https://autodesk.i.lithium.com/t5/image/serverpage/image-id/516281i74784B88B7BE4B86/image-size/large?v=1.0&px=999"/>',
            GFERP__UPC__c = '888444555444'
            
        );
        insert ItemRecord;
        
        GFERP__Item_Unit_of_Measure__c ItemUnitMeasureRecord = new GFERP__Item_Unit_of_Measure__c(
            Name = 'EA',
            GFERP__Conversion__c = 1,
            GFERP__Item__c = ItemRecord.Id,
            GFERP__Unit_of_Measure__c = UnitMeasureRecord.Id,
            GFERP__Do_Not_Sell__c = false,
            Uploaded_to_CC_Item__c = true,
            Uploaded_to_CC_Item_Date_Time__c = System.now()
        );
        testItemUOMList.add(ItemUnitMeasureRecord);
        
        GFERP__Item_Unit_of_Measure__c ItemUnitMeasureRecord2 = new GFERP__Item_Unit_of_Measure__c(
            Name = 'Pack',
            GFERP__Conversion__c = 1,
            GFERP__Item__c = ItemRecord.Id,
            GFERP__Unit_of_Measure__c = UnitMeasureRecord1.Id,
            GFERP__Do_Not_Sell__c = false,
            Uploaded_to_CC_Item__c = true,
            Uploaded_to_CC_Item_Date_Time__c = System.now()
        );
        testItemUOMList.add(ItemUnitMeasureRecord2);
        insert testItemUOMList;
        
        GFERP__Sales_Price__c SalesPriceRecord = new  GFERP__Sales_Price__c (
            GFERP__Sales_Pricing_Group__c = '',
            GFERP__Active__c = true,
            GFERP__Starting_Date__c = System.today().addDays(-1),
            GFERP__Pricing_Type__c = 'All Accounts',
            GFERP__Ending_Date__c = System.today().addDays(7),
            GFERP__Currency__c = CurrencyRecord.Id
        );
        insert SalesPriceRecord;
        
        for(GFERP__Item_Unit_of_Measure__c ItemUOMRecord : testItemUOMList) {
            
            GFERP__Sales_Price_Entry__c SalesPriceEntryRecord = new GFERP__Sales_Price_Entry__c();
            SalesPriceEntryRecord.GFERP__Item__c = ItemUOMRecord.GFERP__Item__c;
            SalesPriceEntryRecord.GFERP__Minimum_Quantity__c = 2;
            SalesPriceEntryRecord.GFERP__Sales_Price__c = 200;
            SalesPriceEntryRecord.GFERP__Unit_of_Measure__c = ItemUOMRecord.Id;
            SalesPriceEntryRecord.GFERP__Price_Book__c = SalesPriceRecord.Id;
            testSalesPriceEntryRecordList.add(SalesPriceEntryRecord);
            
            GFERP__Sales_Price_Entry__c SalesPriceEntryRecord2 = new GFERP__Sales_Price_Entry__c();
            SalesPriceEntryRecord2.GFERP__Item__c = ItemUOMRecord.GFERP__Item__c;
            SalesPriceEntryRecord2.GFERP__Minimum_Quantity__c = 2;
            SalesPriceEntryRecord2.GFERP__Sales_Price__c = 100;
            SalesPriceEntryRecord2.GFERP__Unit_of_Measure__c = ItemUOMRecord.Id;
            SalesPriceEntryRecord2.GFERP__Price_Book__c = SalesPriceRecord.Id;
            testSalesPriceEntryRecordList.add(SalesPriceEntryRecord2);
            
        }
        
        insert testSalesPriceEntryRecordList;   
        
    }
    
    @isTest
    public static void UploadedSalesPriceTest() {
        
        GFERP__Sales_Price_Entry__c testItemUOM = [SELECT Id, GFERP__Minimum_Quantity__c FROM GFERP__Sales_Price_Entry__c limit 1];
        
        //Assertion
        GFERP__Item_Unit_of_Measure__c testAssertItemUOM  = [SELECT Id, Uploaded_Sales_Price__c, Uploaded_Online_Form_Date__c, Uploaded_Online_To_Date__c FROM GFERP__Item_Unit_of_Measure__c limit 1];
        System.assertEquals(100, testAssertItemUOM.Uploaded_Sales_Price__c);
        System.assertEquals(System.today().addDays(-1), testAssertItemUOM.Uploaded_Online_Form_Date__c);
        System.assertEquals(System.today().addDays(7), testAssertItemUOM.Uploaded_Online_To_Date__c);
        
    }
    
}