force-app/main/default/objects/GFERP__Item__c/GFERP__Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GFERP__Item_Unit_of_Measure__c/GFERP__Item_Unit_of_Measure__c.object-meta.xml
<CustomObject>
    <label>Item Unit of Measure</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Units of Measure</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GFERP__Item_Unit_of_Measure__c/fields/GFERP__Item__c.field-meta.xml
<CustomField>
    <fullName>GFERP__Item__c</fullName>
    <inlineHelpText>The Item associated with this Item Unit of Measure.</inlineHelpText>
    <label>Item</label>
    <referenceTo>GFERP__Item__c</referenceTo>
    <relationshipLabel>Item Units of Measure</relationshipLabel>
    <relationshipName>Item_Unit_of_Measures1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GFERP__Item_Unit_of_Measure__c/fields/Uploaded_to_CC_Item__c.field-meta.xml
<CustomField>
    <fullName>Uploaded_to_CC_Item__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Uploaded to CC Item</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GFERP__Item_Unit_of_Measure__c/fields/Uploaded_to_CC_Item_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Uploaded_to_CC_Item_Date_Time__c</fullName>
    <label>Uploaded to CC Item Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/GFINT_ItemTriggerHandler.cls
//Test Class: GFINT_ItemTriggerHandlerTest
public class GFINT_ItemTriggerHandler {
    
    public static void uncheckedItemUnitOfMeasure(List<GFERP__Item__c> theItemList) {
        
        List<GFERP__Item_Unit_of_Measure__c> theUpdateItemIUMList = new List<GFERP__Item_Unit_of_Measure__c>();
        List<GFERP__Item_Unit_of_Measure__c> theItemUOMList = [SELECT Id, Uploaded_to_CC_Item__c FROM GFERP__Item_Unit_of_Measure__c WHERE GFERP__Item__c IN : theItemList];
        
        for(GFERP__Item_Unit_of_Measure__c theItemUOM : theItemUOMList) {
            
            if(theItemUOM.Uploaded_to_CC_Item__c) {
                theItemUOM.Uploaded_to_CC_Item__c = false;
                theItemUOM.Uploaded_to_CC_Item_Date_Time__c = null;
                theUpdateItemIUMList.add(theItemUOM);
            }
        }
        
        if(!theUpdateItemIUMList.isEmpty()) update theUpdateItemIUMList;
    }
    
}