force-app/main/default/objects/GFERP__Item_Unit_of_Measure__c/GFERP__Item_Unit_of_Measure__c.object-meta.xml
<CustomObject>
    <label>Item Unit of Measure</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Units of Measure</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GFERP__Item_Unit_of_Measure__c/fields/Uploaded_to_CC_Item__c.field-meta.xml
<CustomField>
    <fullName>Uploaded_to_CC_Item__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Uploaded to CC Item</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/GFINT_CreateStorefrontCatalogXML.cls
//Test Class: GFINT_ComCloudItemInventoryBatchTest
public class GFINT_CreateStorefrontCatalogXML implements Queueable, Database.AllowsCallouts{
    
    List<GFERP__Item_Unit_of_Measure__c> theAllItemUOMList = new List<GFERP__Item_Unit_of_Measure__c>();
    Map<Id, List<GFERP__Item_Unit_of_Measure__c>> theItemId_ItemUOMListMap = new Map<Id, List<GFERP__Item_Unit_of_Measure__c>>();
    public GFINT_CreateStorefrontCatalogXML(Map<Id , List<GFERP__Item_Unit_of_Measure__c>> itemUOMMap, List<GFERP__Item_Unit_of_Measure__c> itemUOMList) {
        theItemId_ItemUOMListMap = itemUOMMap;
        theAllItemUOMList = itemUOMList;
    }
    
    public void execute(QueueableContext context) { 
        
        List<GFERP__Item_Unit_of_Measure__c> theItemUOMList = new List<GFERP__Item_Unit_of_Measure__c>();
        for(GFERP__Item_Unit_of_Measure__c theItemUOM : theAllItemUOMList) {
            
            if(!theItemUOM.Uploaded_to_CC_Item__c) theItemUOMList.add(theItemUOM);
            
        }
        
        //get Catalog XML
        String theCatalogProductDataFile = GFINT_AllXMLs.createStorefrontCatalogXML(theItemUOMList, theItemId_ItemUOMListMap);
        
        //API Call
        if(theCatalogProductDataFile != '' && theCatalogProductDataFile != null) {
            GFINT_XMLAPItoSFCC.uploadFileAPI(theCatalogProductDataFile, 'drops_storefront_catalog','catalogs','XML');
        }
        
    }   
}